'''title'''
__title__ = 'videofetch'
'''description'''
__description__ = 'VD: A lightweight video downloader written in pure python'
'''url'''
'''version'''
__version__ = '1.11.8'
'''license'''
__license__ = 'MIT'
